CREATE TABLE IF NOT EXISTS requests_info (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(40) NOT NULL,
    uri varchar(40) NOT NULL,
    ip varchar(40) NOT NULL,
    requested_at timestamp NOT NULL,
    CONSTRAINT PK_REQUESTS_INFO PRIMARY KEY (id)
);